export const queryPreCalculator: QueryPreQuestionnaire = (
  lang,
  slug,
) => `*[_type == "preCalculator" && _lang == "${lang}" && questionnaireSlug.current == "${slug}"] {
  _id,
  _lang,
  preCalculatorName,
  seoDescription,
  seoImage{
    asset->{
      url,
      metadata{
        dimensions{
          height,
          width
        }
      }
    }
  },
  preventIndexing,
  question{
    ...
  },
  boxSelector[]{
    _key,
    boxContent,
    label,
    extraInfo,
    boxIcon->{
      name,
      iconImage{
        asset->{
          url,
          metadata{
            dimensions{
              height,
              width
            }
          }
        }
      }
    },
    calculatorPage->{
      _id,
      _lang,
      _type,
      questionnaireName,
      questionnaireSlug,
    },
  },
  nextButtonText
}`;